export const UPDATE_USERDATA = 'UPDATE_USERDATA';
export const UPDATE_USERSTATE = 'UPDATE_USERSTATE';
export const DELETE_TICKETTYPE = 'DELETE_TICKETTYPE';
export const GET_TICKETTYPES = 'GET_TICKETTYPES';
export const UPDATE_TICKETTYPES = 'UPDATE_TICKETTYPES';
export const ADD_TICKETTYPES = 'ADD_TICKETTYPES';
export const MODIFY_USERDATA = 'MODIFY_USERDATA';
// cart items
export const ADD_ITEM = 'ADD_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const LOAD_CART = 'LOAD_CART';
export const BUY_ALL_ITEMS = 'BUY_ALL_ITEMS';
export const RESET_STORE = 'RESET_STORE';